name: flutter_weather_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  pull_to_refresh: ^2.0.0
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  json_serializer: ^0.2.0
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/
